version: "3.9"

services:
  app:
    user: "1000:1000"
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=user
      - DB_PASSWORD=pass
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:alpine3.19
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

volumes:
  dev-db-data:
  dev-static-data:
